/*
 * This source file was generated by the Gradle 'init' task
 */
// package java;

// import org.junit.jupiter.api.Test;

// import LogProducer;

// import static org.junit.jupiter.api.Assertions.*;

// class AppTest {
//     @Test void appHasAGreeting() {
//         LogProducer classUnderTest = new LogProducer();
//         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//     }
// }
