global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'java_consumer'
    metrics_path: '/metrics'
    static_configs:
      # host.docker.internal points to your Windows machine where the Gradle app runs
      - targets: ['host.docker.internal:8080']